In [1]:
import numpy as np
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
#create two numpy array of size 3x2 and 2x3
array1=np.array([[1,2],[3,4],[5,6]])
array2=np.array([[1,2,3],[4,5,6]])
print(array1)
print(array2)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]


In [4]:
#randomly initialize array
array=np.random.rand(3,2)
print(array)

[[0.86584648 0.86923403]
 [0.73039306 0.55780478]
 [0.73221476 0.51467967]]


In [5]:
#matrix multiplication
mul=np.dot(array1,array2)
print(mul)

[[ 9 12 15]
 [19 26 33]
 [29 40 51]]


In [6]:
#perform elementwise matrix multiplication
mulele1=np.multiply(array1,array1)
mulele2=np.multiply(array2,array2)
print(mulele1)
print(mulele2)

[[ 1  4]
 [ 9 16]
 [25 36]]
[[ 1  4  9]
 [16 25 36]]


In [7]:
#find mean of first matrix
mean=np.mean(array1)
print("Mean of matrix1:",mean)

Mean of matrix1: 3.5


In [8]:
#Convert Numeric entries(columns) of mtcars.csv to Mean Centered Version
data=pd.read_csv('/content/drive/MyDrive/SEM7/ML/Lab1/mtcars.csv')
del data['model']
meancenter=data.apply(lambda x: x-x.mean())
print(meancenter.head())

        mpg     cyl        disp       hp  ...      vs       am    gear    carb
0  0.909375 -0.1875  -70.721875 -36.6875  ... -0.4375  0.59375  0.3125  1.1875
1  0.909375 -0.1875  -70.721875 -36.6875  ... -0.4375  0.59375  0.3125  1.1875
2  2.709375 -2.1875 -122.721875 -53.6875  ...  0.5625  0.59375  0.3125 -1.8125
3  1.309375 -0.1875   27.278125 -36.6875  ...  0.5625 -0.40625 -0.6875 -1.8125
4 -1.390625  1.8125  129.278125  28.3125  ... -0.4375 -0.40625 -0.6875 -0.8125

[5 rows x 11 columns]
